version: '3.4'

services:
  coingardenworldserver:
    image: ${DOCKER_REGISTRY-}coingardenworld.server:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Server/Dockerfile

  coingardenworldserverapi:
    image: ${DOCKER_REGISTRY-}coingardenworld.serverapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ServerAPI/Dockerfile

  coingardenworldwebstatus:
    image: ${DOCKER_REGISTRY-}coingardenworld.webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: WebStatus/Dockerfile
