version: '3.4'

services:
  coingardenworldserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ServerApiUrlHC=http://coingardenworldserverapi/hc
    ports:
      - 30934:80
      - 44314:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  coingardenworldserverapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - CorsPolicies__WebStatusDocker=http://coingardenworldwebstatus
    ports:
      - 42254:80
      - 44363:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  coingardenworldwebstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - HealthChecksUI__HealthChecks__0__Name=Server API HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://coingardenworldserverapi/hc
      - HealthChecksUI__HealthChecks__1__Name=Server HTTP Check
      - HealthChecksUI__HealthChecks__1__Uri=http://coingardenworldserver/hc
    ports:
      - 43124:80
      - 44364:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro